version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydatabase
    depends_on:
      - db
    command: python app.py
    restart: always

  web2:
    build: .
    ports:
      - "5001:5000"
    environment:
      DATABASE_URL: postgresql://myuser2:mypassword2@db2:5432/products
    depends_on:
      - db2
    command: python app2.py
    restart: always
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data1:/var/lib/postgresql/data

  db2:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser2
      POSTGRES_PASSWORD: mypassword2
      POSTGRES_DB: products
    ports:
      - "5434:5432"
    volumes:
      - postgres_data2:/var/lib/postgresql/data

  api:
    build: Api_conexion/.
    ports:
      - "5003:5000"
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydatabase
    depends_on:
      - db
      - db2
    command: python autentificacion_completo.py

  auten:
    build: Autentificacion/.
    ports:
      - "5005:5000"
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydatabase
    depends_on:
      - db
    restart: always

volumes:
  postgres_data1:
  postgres_data2:
